repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: update-json-def-files
        name: Update json and def files
        entry: pre-commit-hooks/update-json-def-files.sh
        language: system
        files: ^schema/.*/.*-source.yaml$
