#!/usr/bin/env python3
"""convert yaml on stdin to json on stdout"""

import json
import sys
import yaml

json.dump(yaml.load(sys.stdin, Loader=yaml.SafeLoader), sys.stdout, indent=3, sort_keys=False)
