name: checks
on: [push, pull_request]
jobs:
  precommit_hooks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmd:
          - "check-added-large-files"
          - "trailing-whitespace"
          - "end-of-file-fixer"
          - "mixed-line-ending"
          - "update-json-def-files"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: ${{ matrix.cmd }} --all-files
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: install dependencies
        run: python3 -m pip install -r .requirements.txt

      - name: attempt docs build
        working-directory: docs
        run: make all
