name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: Stale
        stale-issue-message: >-
          This issue was marked stale due to inactivity.
        stale-pr-label: Stale
        stale-pr-message: >-
          This pull request was marked stale due to inactivity.
        days-before-stale: 60
        days-before-close: 14
        exempt-issue-labels: "Stayin' Alive"
